public enum LevelUpId
{
    ADD_HP,
    ADD_AMOUR,
    INCREASE_MAX_HP_PERCENT,
    INCREASE_MAX_AMOUR_PERCENT,
    LOSE_CURRENT_HP_PERCENT,
    INCREASE_EXP,
    ADD_HP_PERCENT,
    LOSE_POINT_PERCENT,
    RESET_COOL_DOWN_ALL_SKILL
}